# kernel.0

import os

Import('env', 'fkernelPath')
senv = env.Clone()

fkernelExec = os.path.basename(fkernelPath)

senv.Command('FKernel.img', '#build/bootdict/bootdict-x86.img',  Copy('$TARGET', '$SOURCE'))
senv.Command(fkernelExec, fkernelPath, Copy('$TARGET', '$SOURCE'))

sysdict_deps = senv.SConscript('#sysdict/SConstruct-config', exports = ['env'])

kernel_0_src = []
kernel_0_src.extend(sysdict_deps)
kernel_0_src.extend(senv.Glob('#lib/~ik/*.4th'))
kernel_0_src.extend(senv.Glob('#lib/~js/486asm/*.F'))
kernel_0_src.extend(senv.Glob('#lib/~js/486asm/*.4th'))

kernel_0_deps = []
kernel_0_deps.extend(senv.Glob('*.4th'))
kernel_0_deps.extend(kernel_0_src)

senv.Command('IKForth.img',
        fkernelExec,
        'IKFORTHTERMINIT=${TERMINIT} ${BUILD_LAUNCHER} ${SOURCE} ${TARGET}')
senv.Depends('IKForth.img', ['FKernel.img', fkernelExec, kernel_0_deps])
