# image

Import('env')
senv = env.Clone()

senv.Command('FKernel.img',
        senv.Glob('*.asm'),
        'fasm -d CODE_THREADING=${CODE_THREADING_TYPE} -d DEBUG=${DEBUG} $SOURCE -s ${TARGET.dir}/FKernel.sym $TARGET')

senv.Command('FKernel.lst',
        ['FKernel.sym', 'FKernel.img'],
        'listing $SOURCE $TARGET')

senv.SideEffect('FKernel.sym', 'FKernel.img')
senv.Alias('image', ['FKernel.img', 'FKernel.lst'])
