;******************************************************************************
;
;  words.inc
;  IKForth
;
;  Copyright (C) 1999-2004 Illya Kysil
;
;******************************************************************************

                        INCLUDE "host.inc"
                        INCLUDE "primitives.inc"
                        INCLUDE "varconst.inc"
                        INCLUDE "ik.inc"
                        INCLUDE "source.inc"
                        INCLUDE "thread.inc"
                        INCLUDE "int_comp.inc"
                        INCLUDE "interpret.inc"
                        INCLUDE "header.inc"
                        INCLUDE "stack.inc"
                        INCLUDE "rstack.inc"
                        INCLUDE "math.inc"
                        INCLUDE "compare.inc"
                        INCLUDE "memory.inc"
                        INCLUDE "search.inc"
                        INCLUDE "fcontrol.inc"
                        INCLUDE "parse.inc"
                        INCLUDE "data.inc"
                        INCLUDE "string.inc"
                        INCLUDE "double.inc"
                        INCLUDE "convert.inc"
                        INCLUDE "except.inc"
                        INCLUDE "file.inc"

