#
#  Makefile for IKForth.
#
#  Copyright (C) 1999-2003 Illya Kysil
#

watcom = T:\OpenWatcom\binnt
asm = $(watcom)\wasm.exe
disasm = $(watcom)\wdis.exe
link = $(watcom)\wlink.exe
make = $(watcom)\wmake.exe

all :   IKForth.exe IKForth.img

IKForth.exe : src\FKernel.exe
        echo Building $@
        copy src\FKernel.exe IKForth.exe > nul

IKForth.img : src\FKernel.img &
              src\*.f src\kernel\*.f src\kernel.0\*.f lib\win32\*.f &
              lib\ansi\*.f lib\~ik\*.f lib\~js\486asm\*.f
        echo Building $@
        src\FKernel.exe

src\FKernel.img : src\FKernel.exe src\image\*.asm src\image\*.inc
        echo Building $@
        cd  src\image
        $(asm) -e2 -3ps -mf -bt=nt FKernel.asm -q
        $(link) file FKernel.obj system nt op map op q op offset=0 name ..\FKernel.img
        $(disasm) -l=FKernel.lst ..\FKernel.img
        cd  ..\..

src\FKernel.exe : src\loader\*.cpp src\loader\*.hpp
        echo Building $@
        cd  src\loader\win32
        $(make) $(__MAKEOPTS__)
        copy FKernel.exe ..\..\FKernel.exe > nul
        cd  ..\..\..

clean : .symbolic
        del src\image\*.obj
        del src\image\FKernel.lst
        del src\FKernel.img
        del src\FKernel.exe
        cd  src\loader\win32
        $(make) clean $(__MAKEOPTS__)
        cd  ..\..\..
