\
\  source.tpl
\
\  Copyright (C) 1999-2003 Illya Kysil
\

CR .( Loading SOURCE definitions )

CREATE-REPORT @
CREATE-REPORT OFF

: SAVE-INPUT-HOOK-DEFAULT ;

DEFER SAVE-INPUT-HOOK ' SAVE-INPUT-HOOK-DEFAULT IS SAVE-INPUT-HOOK

: RESTORE-INPUT-PROC: (S -- xt[RESTORE-INPUT-PROC] )
  :NONAME POSTPONE >R
;

: ;RESTORE-INPUT-PROC (S -- )
  POSTPONE R> POSTPONE OR POSTPONE ;
; IMMEDIATE/COMPILE-ONLY

: SAVE-INPUT-PROC: (S -- xt[SAVE-INPUT-PROC] )
  :NONAME POSTPONE >R
;

: (SAVE-INPUT-PROC) POSTPONE LITERAL POSTPONE LITERAL POSTPONE R> POSTPONE +
  DEFER@ SAVE-INPUT-HOOK COMPILE,
; COMPILE-ONLY

: ;SAVE-INPUT-PROC (S xt[RESTORE-INPUT-PROC] xt[SAVE-INPUT-PROC] n -- )
  SWAP >R 1+ SWAP
  (SAVE-INPUT-PROC) POSTPONE ;
  R> IS SAVE-INPUT-HOOK
; IMMEDIATE/COMPILE-ONLY

: IK-SAVE-INPUT 0 SAVE-INPUT-HOOK ;
: IK-RESTORE-INPUT
  ?DUP 0<>
  IF 
    FALSE           \ n1 xt1 n flag
    BEGIN
      SWAP          \ n1 xt1 flag n 
      ?DUP          \ n1 xt1 flag n
    WHILE
      SWAP >R       \ n1 xt1 n
      SWAP >R       \ n1 n
      OVER - 2 -    \ n1 n-n1-2
      R> SWAP       \ n1 xt1 n-n1-2
      R> -ROT >R    \ n1 flag xt1
      EXECUTE R> SWAP
    REPEAT
  ELSE
    FALSE
  THEN
;

\ RESTORE-INPUT-PROC: . . FALSE ;RESTORE-INPUT-PROC
\ SAVE-INPUT-PROC: 1 1 [ 2 ] ;SAVE-INPUT-PROC 

CREATE-REPORT !
