\
\  words.f
\
\  Copyright (C) 1999-2001 Illya Kysil
\

S" KERNEL\ANSI-EC.F"      INCLUDED
S" KERNEL\IKFORTH.F"      INCLUDED
S" KERNEL\CHAIN.F"        INCLUDED

:NONAME INIT-USER ;
CHAIN STARTUP-CHAIN

:NONAME ;
CHAIN SHUTDOWN-CHAIN

S" KERNEL\DLLINTF.F"      INCLUDED

S" KERNEL\DOUBLE.F"       INCLUDED
S" KERNEL\FORMAT.F"       INCLUDED
S" KERNEL\SEARCH-ORDER.F" INCLUDED
S" KERNEL\REQUIRED.F"     INCLUDED
S" KERNEL\ENVIRONMENT.F"  INCLUDED
S" KERNEL\EXCEPTION.F"    INCLUDED
S" KERNEL\QUIT.F"         INCLUDED
S" KERNEL\BLOCK.F"        INCLUDED
S" KERNEL\CASE.F"         INCLUDED
S" KERNEL\TOOLS.F"        INCLUDED
S" KERNEL\MARKER.F"       INCLUDED

S" KERNEL\STRING.F"       INCLUDED
S" KERNEL\VALUE.F"        INCLUDED

S" WIN\CONSTS.F"          INCLUDED
\ S" WIN\WINCON.F"          INCLUDED
S" WIN\KERNEL32.F"        INCLUDED
S" WIN\CONSOLE.F"         INCLUDED

S" KERNEL\MEMORY.F"       INCLUDED
S" KERNEL\MISC.F"         INCLUDED
S" KERNEL\FILE.F"         INCLUDED
S" KERNEL\LOCALS.F"       INCLUDED
S" KERNEL\SEE.F"          INCLUDED
S" EXT\LOOP.F"            INCLUDED
S" EXT\CLASS.F"           INCLUDED

S" EXT\486ASM-IKF-PRE.F"  INCLUDED
S" EXT\486ASM\486ASM.F"   INCLUDED
S" EXT\486ASM-IKF-POST.F" INCLUDED
