# loader-win32

Import('env')
senv = env.Clone()

senv['OS_TARGET'] = 'nt'

senv['CXX'] = 'owcc'
senv['CCFLAGS'] = '-mconsole -mregparm=0 -Wall -zq -O3 -mtune=586 -mcmodel=f -D__USE_MISC'

senv['LINKFLAGS'] = '-b $OS_TARGET -k4k -g0 -s'

senv.Alias('loader', ['FKernel.exe'])

loader_src = senv.Glob('*.cpp')
loader_src.extend(senv.Glob('sys$OS_TARGET/*.cpp'))

senv.Program('FKernel.exe',
        loader_src,
        CPPPATH = ['.', '$WATCOM/h', '$WATCOM/h/nt', '$WATCOM/lh'])

