\
\  loop.f
\
\  Copyright (C) 1999-2001 Illya Kysil
\

\ -----------------------------------------------------------------------------
\ LOOPS EXT
\ -----------------------------------------------------------------------------

: +DO POSTPONE OVER POSTPONE MIN POSTPONE ?DO ; IMMEDIATE/COMPILE-ONLY

: UMIN 2DUP U> IF SWAP THEN DROP ;

: U+DO POSTPONE OVER POSTPONE UMIN POSTPONE ?DO ; IMMEDIATE/COMPILE-ONLY

: -LOOP POSTPONE NEGATE POSTPONE +LOOP
        POSTPONE ELSE POSTPONE 2DROP
        POSTPONE THEN ; IMMEDIATE/COMPILE-ONLY

: -DO POSTPONE 2DUP POSTPONE < POSTPONE IF
      POSTPONE SWAP POSTPONE 1+ POSTPONE SWAP POSTPONE DO ; IMMEDIATE/COMPILE-ONLY

: U-DO POSTPONE 2DUP POSTPONE U< POSTPONE IF
       POSTPONE SWAP POSTPONE 1+ POSTPONE SWAP POSTPONE DO ; IMMEDIATE/COMPILE-ONLY
