PURPOSE: WINMISC definitions
LICENSE: Unlicense since 1999 by Illya Kysil

REPORT-NEW-NAME @
REPORT-NEW-NAME OFF

USER TIME&DATE-STRUC 16 USER-ALLOC

:NONAME (S -- +n1 +n2 +n3 +n4 +n5 +n6 )
   TIME&DATE-STRUC
   DUP GetLocalTime
   DUP 6 WORDS+ W@ SWAP
   DUP 5 WORDS+ W@ SWAP
   DUP 4 WORDS+ W@ SWAP
   DUP 3 WORDS+ W@ SWAP
   DUP 1 WORDS+ W@ SWAP
   DUP 0 WORDS+ W@ SWAP
   DROP
; IS TIME&DATE

REPORT-NEW-NAME !
