\
\  consts.f
\
\  Copyright (C) 1999-2001 Illya Kysil
\

CR .( Loading CONSTS definitions )

CREATE-REPORT @
CREATE-REPORT OFF

0 CONSTANT NIL

$    0          CONSTANT GMEM_FIXED
$    2          CONSTANT GMEM_MOVEABLE
$   10          CONSTANT GMEM_NOCOMPACT
$   20          CONSTANT GMEM_NODISCARD
$   40          CONSTANT GMEM_ZEROINIT
$   80          CONSTANT GMEM_MODIFY
$  100          CONSTANT GMEM_DISCARDABLE
$ 1000          CONSTANT GMEM_NOT_BANKED
$ 2000          CONSTANT GMEM_SHARE
$ 2000          CONSTANT GMEM_DDESHARE
$ 4000          CONSTANT GMEM_NOTIFY
$ 8000          CONSTANT GMEM_INVALID_HANDLE

GMEM_NOT_BANKED CONSTANT GMEM_LOWER

32626           CONSTANT GMEM_VALID_FLAGS

GMEM_MOVEABLE GMEM_ZEROINIT OR CONSTANT GHND
GMEM_FIXED    GMEM_ZEROINIT OR CONSTANT GPTR

-10 CONSTANT STD_INPUT_HANDLE
-11 CONSTANT STD_OUTPUT_HANDLE
-12 CONSTANT STD_ERROR_HANDLE

1 CONSTANT KEY_EVENT

CREATE-REPORT !
