CR
.( TESTING SEARCH ) CR

: T S" 123" 2SWAP 2DUP ." SEARCHING: " TYPE 9 EMIT SEARCH
  FALSE = IF ." NOT " THEN ." FOUND: " TYPE CR ;

S" 1"    T
S" 12"   T
S" 23"   T
S" 31"   T
S" 3"    T
S" 1A"   T
S" 234"  T
S" 1234" T