# image

Import('env_bootdict')
senv = env_bootdict.Clone()
senv['bootdictname'] = 'bootdict-${ARCH}' 

bootdict_src = []
bootdict_src.extend(senv.Glob('#bootdict/*.asm'))
bootdict_src.extend(senv.Glob('#bootdict/tc/*.asm'))
bootdict_src.extend(senv.Glob('#bootdict/${ARCH}/*.asm'))
bootdict_src.extend(senv.Glob('#bootdict/${ARCH}-itc/*.asm'))
bootdict_src.extend(senv.Glob('#bootdict/${ARCH}-dtc/*.asm'))

senv.Command('${bootdictname}.img',
        bootdict_src,
        'fasm -d CODE_THREADING=${CODE_THREADING_TYPE} -d DEBUG=${DEBUG} bootdict/${bootdictname}.asm -s ${TARGET.dir}/${bootdictname}.sym $TARGET')

senv.Command('${bootdictname}.lst',
        ['${bootdictname}.sym', '${bootdictname}.img'],
        'listing $SOURCE $TARGET')

senv.SideEffect('${bootdictname}.sym', '${bootdictname}.img')
senv.Alias('${bootdictname}', ['${bootdictname}.img', '${bootdictname}.lst'])
