Import('env_bootdict')
senv = env_bootdict.Clone()
senv['bootdictname'] = 'bootdict-${ARCH}'

bootdict_src = []
bootdict_src.extend(senv.Glob('#bootdict/*.asm'))
bootdict_src.extend(senv.Glob('#bootdict/tc/*.asm'))
bootdict_src.extend(senv.Glob('#bootdict/${ARCH}/*.asm'))
bootdict_src.extend(senv.Glob('#bootdict/${ARCH}-itc/*.asm'))
bootdict_src.extend(senv.Glob('#bootdict/${ARCH}-dtc/*.asm'))

bootdict = senv.Command('${bootdictname}.img',
        bootdict_src,
        'fasm -d CODE_THREADING=${CODE_THREADING_TYPE} -d DEBUG=${DEBUG} bootdict/${bootdictname}.asm -s ${TARGET.dir}/${bootdictname}.sym $TARGET')

bootdict_listing = senv.Command('${bootdictname}.lst',
        ['${bootdictname}.sym', '${bootdictname}.img'],
        'listing $SOURCE $TARGET')

senv.Alias('bootdict-listing', bootdict_listing)

senv.SideEffect('${bootdictname}.sym', bootdict)
senv.Alias('bootdict', [bootdict, bootdict_listing])

Return('bootdict')
